### ISSUE TITLE
Updating to openapi-fetch@0.13.2 Breaks TypeScript

### ISSUE THREAD

**Issue by ryanelian** [openapi-ts/openapi-typescript#2035] opened 2024-12-04 02:30 UTC
Updating from `"openapi-fetch": "0.13.0"` to `"openapi-fetch": "0.13.2"` causes types to become unavailable.

<img width="876" alt="image" src="https://github.com/user-attachments/assets/9d7bd009-2bb4-410e-bafa-83867a14f713">

I am using TypeScript version `"typescript": "5.7.2"` and Visual Studio Code latest version.

**Comment by ryanelian** [comment] 2024-12-04 02:33
<img width="315" alt="image" src="https://github.com/user-attachments/assets/45293c30-02b5-45b9-bfa6-47cb84752929">

<img width="409" alt="image" src="https://github.com/user-attachments/assets/fd57d4cd-8ba2-4be3-b707-b51fed1460e9">

Folder and Manifest do not match.

**Comment by eksno** [comment] 2024-12-04 04:28
+1 broken for me too

```
Error: Failed to resolve entry for package "openapi-fetch". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16287:15)
    at resolvePackageEntry (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16284:3)
    at tryNodeResolve (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:16149:18)
    at ResolveIdContext.resolveId (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:15934:19)
    at EnvironmentPluginContainer.resolveId (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:46930:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformPluginContext.resolve (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:47089:15)
    at async normalizeUrl (file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:45419:26)
    at async file:///app/node_modules/.pnpm/vite@6.0.2_@types+node@22.10.1_jiti@2.4.1_terser@5.36.0_yaml@2.6.1/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:45550:39
    at async Promise.all (index 0) {
  code: 'ERR_RESOLVE_PACKAGE_ENTRY_FAIL',
  pos: 26,
  plugin: 'vite:import-analysis',
  id: '/app/src/lib/api/index.ts',
  pluginCode: 'import createClient from "openapi-fetch";\n' +
    'import { PUBLIC_API_URL } from "$env/static/public";\n' +
    'import { getURL } from "$lib/utils.ts";\n' +
    'const api = createClient({ baseUrl: getURL(PUBLIC_API_URL) });\n' +
    'export default api;\n',
  loc: { file: '/app/src/lib/api/index.ts', line: 1, column: 25 },
  frame: '1  |  import createClient from "openapi-fetch";\n' +
    '   |                            ^\n'
}
```

**Comment by bkis** [comment] 2024-12-04 06:42
I suspect this is because of #2032 – right?

**Comment by boyer-nicolas** [comment] 2024-12-04 12:09
It looks like it's also related to https://github.com/openapi-ts/openapi-typescript/actions/runs/12129439515/job/33817861940 

The build did not go through but the package was published anyway, branch protection rules need to be enforced to prevent this.

**Comment by gzm0** [comment] 2024-12-04 14:50
> It looks like it's also related to https://github.com/openapi-ts/openapi-typescript/actions/runs/12129439515/job/33817861940

I think this is just a downstream issue: openapi-fetch wasn't built properly, so then swr-openapi (which depends on it) failed to build. From the log alone, it looks like the openapi-fetch publish completed "successfully".

**Comment by gzm0** [comment] 2024-12-04 14:50
I'm going to close this as dupe of #2032, because they have the same root cause.

**Closed by gzm0** 2024-12-04 14:50 UTC
Labels: bug, openapi-fetch

**Comment by drwpow** [comment] 2024-12-04 15:54
openapi-fetch and openapi-react-query got refreshes (you’ll have to update to the latest patch; for obvious reasons npm doesn’t let you re-publish a version), and confirmed the `dist/` folder was published correctly. Sorry for the inconvenience!
