### ISSUE TITLE
Different error types from backend/API for same path 

### ISSUE THREAD

**Issue by jozekuhar** [openapi-ts/openapi-typescript#1894] opened 2024-09-02 11:43 UTC
**Description**

Backend has different error responses for one path (`responses` below) but only first error type is accessible in frontend/typescript. 

```
responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorTest"];
                };
            };
        };
```

Error type in typescript is `components["schemas"]["Message"];`, which is `{ detail: string }`. Other errors are ignored.

So `error` type in typescript is `const error: { detail: string } | undefined`.

**Reproduction**

You can write backend app with multiple errors for same path.

**Expected result**

I was expecting I will get all possible error types: `TError401 | TError404 | undefined`. 

I tested this same thing for multiple success types (2xx) and it was correctly made union for 2 types, for 3 status codes last type was `{}` instead of `{ key: string }`

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

**Comment by drwpow** [comment] 2024-09-02 12:04
Duplicate of #1723

**Closed by drwpow** 2024-09-02 12:04 UTC
Labels: bug, openapi-fetch
