### ISSUE TITLE
The `duplex` member must be specified for a request with a streaming body

### ISSUE THREAD

**Issue by kevinhikaruevans** [openapi-ts/openapi-typescript#1729] opened 2024-06-24 17:10 UTC
**Description**

This is my first time seeing this issue after using this library for a while. But I've noticed that when I do a POST to an endpoint, like:

```ts
client.POST('/api/dsr/rows/validate', {
     body: {action: 'Move', action_data: 'a', bot_id: 1, step: 1, status: 'NotStarted', uuid: '1'}
})
```

It raises this error:

```
openapi-fetch.js?v=53b3da91:100 Uncaught (in promise) 
TypeError: Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body
    at coreFetch (openapi-fetch.js?v=53b3da91:100:26)
    at Object.POST (openapi-fetch.js?v=53b3da91:147:14)
    at DSRGrid (DSRGrid.tsx:47:12)
    at renderWithHooks (chunk-YDDRBQTN.js?v=53b3da91:11548:26)
    at updateFunctionComponent (chunk-YDDRBQTN.js?v=53b3da91:14587:32)
```

...which seems odd, considering I'm just passing in a simple object. I'm also doing a couple GETs and those work just fine.

**Reproduction**

This seems to only happen in Chrome. I'm using Version 125.0.6422.141 (Official Build) (64-bit). In Firefox (127.0.1 (64-bit)) this works as expected. I've also tried using a `bodySerializer` w/ `JSON.stringify`-ing the object.

I'm using FastAPI as the backend using a simple endpoint that basically does nothing:
```py
    @router.post('/rows/validate')
    def validate_row(row: Row) -> Row:
        return row
```
Note that this endpoint doesn't actually get hit by the client. It's failing before the request is sent. The relevant OpenAPI stuff looks like this:

```json
    "/api/dsr/rows/validate": {
      "post": {
        "summary": "Validate Row",
        "operationId": "validate_row_api_dsr_rows_validate_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Row-Input"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Row-Output"
                }
              }
            }
          },
          "404": {
            "description": "not found"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
```

with Row-Input looking like:

```json
      "Row-Input": {
        "properties": {
          "uuid": {
            "type": "string",
            "format": "uuid4",
            "title": "Uuid"
          },
          "step": {
            "type": "integer",
            "title": "Step"
          },
          "bot_id": {
            "type": "integer",
            "title": "Bot Id"
          },
          "action": {
            "type": "string",
            "enum": [
              "Move",
              "etc..."
            ],
            "title": "Action"
          },
          "action_data": {
            "anyOf": [
              {
                "$ref": "#/components/schemas/Coord"
              },
              {
                "items": {
                  "$ref": "#/components/schemas/DispenseData"
                },
                "type": "array"
              },
              {
                "type": "number"
              },
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Action Data"
          },
          "status": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "NotStarted",
                  "InProgress",
                  "Done"
                ]
              },
              {
                "type": "null"
              }
            ],
            "title": "Status",
            "default": "NotStarted"
          }
        },
        "type": "object",
        "required": [
          "step",
          "bot_id",
          "action",
          "action_data"
        ],
        "title": "Row"
      },
```

**Expected result**

It should do a POST

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

I can do a PR if I can figure out what is happening.

**Comment by drwpow** [comment] 2024-06-24 17:11
Duplicate of https://github.com/openapi-ts/openapi-typescript/issues/1715. This has been resolved in `0.10.0`.

**Closed by drwpow** 2024-06-24 17:11 UTC
Labels: bug, openapi-fetch
