### ISSUE TITLE
openapi-react-query: infinite queries

### ISSUE THREAD

**Issue by OliverJAsh** [openapi-ts/openapi-typescript#2062] opened 2024-12-20 12:04 UTC
Are there plans to add support for "[infinite queries](https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries)"? If so, I'm curious how this could work. How would the library know how to feed `pageParam` from React Query through to the correct param?

**Comment by kerwanp** [comment] 2024-12-21 12:06
It is definitely planned to support more hooks like `useQueries`, `useInfiniteQuery`, etc for the V1. But before, it requires some refactoring on the type system to be sure that implementations are well done and consistent.

**Comment by kerwanp** [comment] 2024-12-21 12:14
Closing as duplicate of https://github.com/openapi-ts/openapi-typescript/issues/1828

**Closed by kerwanp** 2024-12-21 12:14 UTC
Labels: enhancement, openapi-react-query
