### ISSUE TITLE
when use header and cookie, and use same name(param1), header always return never

### ISSUE THREAD

**Issue by liangskyli** [openapi-ts/openapi-typescript#1798] opened 2024-08-02 01:37 UTC
**Description**

when use header and cookie, and use same name(param1), header always return never

error error
```
header?: never;
```
Expected result
```
header: {
          /** @description param1 */
          param1: string;
        };
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.2.0`                      |
| Node.js              | `18`                      |
| OS + version         | `Windows 10` |

**Reproduction**

_How can this be reproduced / when did the error occur?_

use openapi-v3.json
schema data
```
{
  "openapi": "3.1.0",
  "info": {
    "title": "@liangskyli/routing-controllers-openapi",
    "license": {
      "name": "This file is auto generated by @liangskyli/routing-controllers-openapi, do not edit!"
    },
    "version": "0.7.2"
  },
  "tags": [
    {
      "name": "Test1",
      "description": ""
    }
  ],
  "paths": {
    "/root/v1/getQueryParamWithQueryParams/{path1}/{path2}": {
      "get": {
        "tags": ["Test1"],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "description": "接口返回code码字段"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Response1.63007440"
                    },
                    "msg": {
                      "type": "string",
                      "description": "接口返回信息字段"
                    }
                  },
                  "required": ["code", "data"]
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "param1",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "param1"
          },
          {
            "name": "param1",
            "in": "cookie",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "param1"
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "IParam2.eb9fbc4a": {
        "type": "object",
        "properties": {
          "param1": {
            "description": "param1",
            "type": "string"
          }
        },
        "required": ["param1"]
      },
      "Response1.63007440": {
        "type": "object",
        "properties": {
          "activityBases2": {
            "type": "string"
          }
        },
        "required": ["activityBases2"]
      }
    }
  }
}

```

```
const result = await openapiTS(schema, {});
const  resultString = `${astToString(result)}`;
```

** error result**

```
export interface paths {
  '/root/v1/getQueryParamWithQueryParams/{path1}/{path2}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description param1 */
          param1: string;
        };
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description 接口返回code码字段 */
              code: number;
              data: components['schemas']['Response1.63007440'];
              /** @description 接口返回信息字段 */
              msg?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'IParam2.eb9fbc4a': {
      /** @description param1 */
      param1: string;
    };
    'Response1.63007440': {
      activityBases2: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

```

**Expected result**

```
export interface paths {
  '/root/v1/getQueryParamWithQueryParams/{path1}/{path2}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description param1 */
          param1: string;
        };
        path?: never;
        cookie: {
          /** @description param1 */
          param1: string;
        };
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description 接口返回code码字段 */
              code: number;
              data: components['schemas']['Response1.63007440'];
              /** @description 接口返回信息字段 */
              msg?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'IParam2.eb9fbc4a': {
      /** @description param1 */
      param1: string;
    };
    'Response1.63007440': {
      activityBases2: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

```

_(in case it’s not obvious)_

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment] 2024-08-14 09:40
Thanks for filing! I’m going to mark this as a duplicate of #1771. Would welcome suggestions there on how openapi-fetch should handle it. Cookies can be tricky!

**Comment by liangskyli** [comment] 2024-08-14 10:17
One is the generation problem, and the other is the use problem, which should not be a duplicate bug.





------------------ Original ------------------
From: Drew Powers ***@***.***&gt;
Date: Wed,Aug 14,2024 5:40 PM
To: openapi-ts/openapi-typescript ***@***.***&gt;
Cc: liangsky ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [openapi-ts/openapi-typescript] when use header and cookie, anduse same name(param1), header always return never (Issue #1798)





 
Thanks for filing! I’m going to mark this as a duplicate of #1771. Would welcome suggestions there on how openapi-fetch should handle it. Cookies can be tricky!

**Comment by drwpow** [comment] 2024-08-14 10:23
Oh I see now; my mistake. The use of openapi-fetch threw me off.

I see now—it’s the conflict of the name `param1` that’s likely causing it to get dropped.

PRs would be welcome for this! This should be a nice, easy bug to fix.

**Closed** 2024-08-29 14:46 UTC
Labels: bug, PRs welcome, good first issue, openapi-ts
